# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04" #"debian/buster64" #"bento/ubuntu-22.04"

    # Set CPU and Memory
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    end

    config.vm.define "node-1" do |node|
        node.vm.network "private_network", ip: "192.168.56.24"
        node.vm.hostname = "node-1"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.limit = "all" # Disable default limit to connect to all the nodes
        ansible.playbook = "test_deploy-docker-compose.yml"
        ansible.groups = {
            "server" => ["node-1"],
        }
    end

end
